### INICIAR SESION
POST http://localhost:3000/api/signing

### REGISTRARSE
POST http://localhost:3000/api/signup
Content-Type: application/json

{
    "name": "fazttt",
    "email": "fazttt@gmail.com",
    "password": "fazttt123"
}

### CERRAR SESIÓN
POST http://localhost:3000/api/signout

### PERFIL DE USUARIO
GET http://localhost:3000/api/profile


