### INICIAR SESION
POST http://localhost:3000/api/signing

### REGISTRARSE
POST http://localhost:3000/api/signup
Content-Type: application/json

{
    "name": "karuxxxxxxx",
    "email": "karuxxxxxxx123@gmail.com",
    "password": "karuxxxxxxx123"
}

### CERRAR SESIÓN
POST http://localhost:3000/api/signout

### PERFIL DE USUARIO
GET http://localhost:3000/api/profile


