### INICIAR SESION
POST http://localhost:3000/api/signing

### CERRAR SESIÓN
POST http://localhost:3000/api/signup

### REGISTRARSE
POST http://localhost:3000/api/signout

### PERFIL DE USUARIO
GET http://localhost:3000/api/profile


